### ISSUE TITLE
Extension doesn't work anymore

### ISSUE THREAD

**Issue by Tav0** [arianrhodsandlot/DevDocs-Web-Ext#20]
![Screen Shot 2021-03-09 at 10 38 54 AM](https://user-images.githubusercontent.com/5408896/110496628-ac24c100-80c3-11eb-87bc-41da610c2229.png)

I have tried it in Brave, Canary and Chrome

I have React installed in devdocs.io

**Comment by manutepowa** [comment]
Same issue.

I made a fork from the project and in the search function in search.tsx file I have a "set timeout error".

The error is in try/catch browser polyfill.

![image](https://user-images.githubusercontent.com/6350474/110605781-c32de680-8189-11eb-924d-491495257a8c.png)

**Comment by arianrhodsandlot** [comment]
Publishing the new fixed version to Chrome Web Store. This may take some time since Google has updated its policies so this extension has to be reviewed by them.
