### ISSUE TITLE
Can't see documentations for  enabled documentations

### ISSUE THREAD

**Issue by AlNotAlbert** [arianrhodsandlot/DevDocs-Web-Ext#29]
I am not able to view documentations for anything other than css and html. For example when I type unique_ptr it won't show any methods for cpp. I have tried enabling the documentation as the plugins instructs to, I deleted them the documentations, I tried allowing cookies for devdocs, I tried limited the extensions permissions on devdocs and giving full permissions, I've tried downloading the documentations offline, nothing seems to work. I am still a beginner, so I wouldn't have a clue as how to fix it it.

**Comment by AlNotAlbert** [comment]
![35bb09c73352507d7e4c1f546f4a9a21](https://user-images.githubusercontent.com/87888006/146316997-70079b65-d597-412c-ae6c-2a6eed7d2304.png)
![cde3b165f379246bbddf2572433947d5](https://user-images.githubusercontent.com/87888006/146317000-a761f055-a54f-40b1-af49-d428ade5c36e.png)
![64a9ae1a2db15a0540053ac8bb7ffbeb](https://user-images.githubusercontent.com/87888006/146317001-2dde36bd-bc2b-43fb-a8dc-af38d7fefa6e.png)
![e0e459f7d6b05795793c02b5c3b153d0](https://user-images.githubusercontent.com/87888006/146317003-5d988034-6fcc-4928-abe8-02972dc4badc.png)

**Comment by arianrhodsandlot** [comment]
Thanks for reporting. It's due to getting cookies from `devdocs.io` is not working as expected now.
https://github.com/arianrhodsandlot/DevDocs-Web-Ext/blob/35d2c4af669a45020d541d445373b16ac1e77c29/src/background/index.ts#L11
I'll try to fix it in this weekends and release a new version.
