### ISSUE TITLE
Syntax Highlighting

### ISSUE THREAD

**Issue by AlNotAlbert** [arianrhodsandlot/DevDocs-Web-Ext#30]
Syntax highlighting for the code snippets to match the ones on the website. Right now its just black and white
![33b90f0b865cd53b52c9e3ec9331e1ec](https://user-images.githubusercontent.com/87888006/147381889-f54d2310-8362-4277-898d-aac24f35c149.png)

Also the theme doesn't change to dark when set to dark.
![251c6cb2f0733078ef261ccb26856f58](https://user-images.githubusercontent.com/87888006/147381948-8c044e9c-3307-4059-af95-25e79c787e96.png)

**Comment by arianrhodsandlot** [comment]
Thanks for your feedback. I'm planning to migrate this extension to [Manifest V3](https://developer.chrome.com/docs/extensions/mv3/intro/mv3-migration/), and these problems will be fixed at that time.

**Comment by arianrhodsandlot** [comment]
fixed via https://github.com/arianrhodsandlot/DevDocs-Web-Ext/commit/5b59f900c3b59abd701c9a32e30f21bae1c3a5b6

**Comment by AlNotAlbert** [comment]
Syntax Highlighting no longer working against in the newest version of the extension
