### ISSUE TITLE
Can't search a single documentation using tab

### ISSUE THREAD

**Issue by sprt** [arianrhodsandlot/DevDocs-Web-Ext#4]
The native DevDocs functionality is described [here](http://devdocs.io/help) under "Searching a single documentation". It's not working with this extension. Would be nice to have it!

**Comment by arianrhodsandlot** [comment]
Great suggestion! I'll create a task to remember to do this later.

**Comment by arianrhodsandlot** [comment]
It's now available sinece v0.1.9 🎉.

**Comment by sprt** [comment]
Super useful, thanks a lot for your work!
